services:
  incursion-bot:
    build: .
    image: registry.nemahs.org/incursion-bot
    command: ['--file', '/run/secrets/userData', '-chat', 'incursions', '-nickname', 'IncursionBot' ]
    secrets:
      - userData
    restart: on-failure
    logging:
      driver: local
      options:
        max-size: "10m"
        max-file: "3"

    deploy:
      replicas: 1

secrets:
  userData:
    external:
      true
