version: '3.9'

services:
  incursion-bot:
    build: .
    command: ['--file', '/run/secrets/userData', '--chat', 'testbot']
    secrets:
      - userData
    restart: on-failure
    logging:
      driver: local

secrets:
  userData:
    file: /home/nemahs/userData
