name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: docker-latest
    environment: production
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.23

    - name: Build
      run: | 
        docker buildx bake
        docker push